In [22]:
#Importing Library
import numpy as np
from numpy import dot
from numpy.linalg import norm

# 1)
Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :) В нашем случае вес экзамена равен 0.3, вес домашек - 0.42, вес контрольной - 0.14, вес самостоятельных - 0.14. Например, если за экзамен у вас 7, за домашки 10, за контрольную 8, а за самостоятельные 6, то вы получите отличную оценку 8!

In [2]:

weights = np.array([0.3, 0.42, 0.14, 0.14])
marks = np.array([7, 10, 8, 6])

def result_mark(a, b):
    return round(np.sum(np.multiply(a, b)),0)

result_mark(weights, marks)

8.0

# 2)
Напишите функцию, меняющую все каждое третье (начиная с 0) значение массива целых чисел на заданное число. Например, если на вход поступает массив array([3, 5, 1, 0, -3, 22, 213436]) и число -111, то на выходе должен получиться массив array([-111, 5, 1, -111, -3, 22, -111]).

In [23]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111

def change_array(a,b):    
    array[0:len(a):3] = b
    return a  

change_array(array, number)

array([-111,    5,    1, -111,   -3,   22, -111])

# 3)
Напишите функцию, выдающую индексы «близких» элементов заданных массивов, а именно тех пар элементов, чей модуль разницы не превосходит заданного значения. Например, если на вход поступают массив array([1.5, 0.5, 2, -4.1, -3, 6, -1]), массив array([1.2, 0.5, 1, -4, 3, 0, -1.2]) и число 0.5, то на выходе должен получиться массив array([0, 1, 3, 6]) (важно: не tuple, а одномерный массив типа numpy.ndarray (то есть .ndim от него равно 1)!).


In [17]:
def find_close(a,b, precision):
    return np.array(np.where(((np.abs(a - b))<= precision) == True))[0]

array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4, 3, 0, -1.2])
precision = 0.5
find_close(array1, array2, precision)


array([0, 1, 3, 6])

#  4)
Напишите функцию, которая составляет блочную матрицу из четырех блоков, где каждый блок - это заданная матрица


In [10]:

def block_matrix(block):
    x = np.concatenate((block,block), axis =0)
    return np.concatenate((x, x), axis=1)

block = np.array([[0, 1, 2], [3, 4, 5]])
block_matrix(block)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

#  5)
Напишите функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. Например, если на вход поступает матрица array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) то ответом будет 32.



In [26]:
def diag_prod(a):
    a =  a.diagonal() 
    return np.prod( a[a > 1])
    
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
diag_prod(matrix)

32

# 6)
Для улучшения качества работы некоторых алгоритмов машинного обучения может быть полезно использовать нормализацию данных, чтобы привести признаки в выборке к одному масштабу — а именно, из каждого столбца вычесть среднее его значений и поделить на их стандартное отклонение. Напишите функцию, нормализующую входящую матрицу (по столбцам).

In [12]:

def normalize(matrix):
    s = np.nanstd(matrix, axis=0);
    return np.divide((matrix - np.nanmean(matrix, axis=0)), s, out=np.zeros(matrix.shape), where=s!=0) 
        
        
        
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])
normalize(matrix)



array([[ 0.70710678, -0.39223227,  0.46291005],
       [-1.41421356,  1.37281295,  0.9258201 ],
       [ 0.70710678, -0.98058068, -1.38873015]])

# 7)
Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов array([4, 6, 0, 1]),  на выходе получается массив коэффициентов array([1, 2, 0, 1, -2])

In [13]:
def antiderivative(coefs):
    return np.polyint(coefs )

coefs = np.array([4, 6, 0, 1])
antiderivative(coefs)

array([1., 2., 0., 1., 0.])

# 8)
Напишите функцию, делающую данную треугольную матрицу симметричной. 

In [14]:
def make_symmetric(matrix):
    return np.maximum( matrix, matrix.transpose() ) 


matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
make_symmetric(matrix)


array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 3,  6,  8,  9],
       [ 4,  7,  9, 10]])

# 9)
Напишите функцию, создающую прямоугольную матрицу из m одинаковых строк, заполненных последовательными натуральными числами от a до b включительно в возрастающем порядке. 


In [21]:
def construct_matrix(m, a, b):
    return  np.full((m, b-a+1),[np.arange(a,b+1)])
m = 5
a = 3
b = 10
construct_matrix(m, a, b)


array([[ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

# 10)
Напишите функцию, вычисляющую косинусную близость двух векторов. Например, если на вход поступают вектора array([-2, 1, 0, -5, 4, 3, -3]) и array([0, 2, -2, 10, 6, 0, 0]), ответом будет -0.25.

In [23]:
def cosine_similarity(vec1, vec2):
    return dot(vec1, vec2)/(norm(vec1)*norm(vec2))

vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])

cosine_similarity(vec1, vec2)

-0.25